# Generated by Django 3.1.3 on 2022-07-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220724_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='course',
            new_name='question',
        ),
    ]
